# Generated by Django 4.0.6 on 2024-07-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='cages')),
            ],
        ),
    ]
