# Generated by Django 4.0.6 on 2024-07-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Nombre')),
                ('link_gmap', models.URLField(blank=True, null=True, verbose_name='Link Google Maps')),
            ],
        ),
    ]
