# Generated by Django 3.2.6 on 2024-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Colonia'),
        ),
    ]
