# Generated by Django 3.2.6 on 2024-07-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0002_alter_colony_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='gmap_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Colonia'),
        ),
    ]
