# Generated by Django 3.2.6 on 2024-07-23 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0003_auto_20240723_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colony',
            old_name='gmap_link',
            new_name='link_gmap',
        ),
    ]
