# Generated by Django 3.2.6 on 2024-07-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0004_rename_gmap_link_colony_link_gmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colony',
            name='link_gmap',
            field=models.URLField(blank=True, null=True, verbose_name='Link Google Maps'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Nombre'),
        ),
    ]
