# Generated by Django 4.0.6 on 2024-09-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Download',
        ),
    ]
