# Generated by Django 3.2.6 on 2024-07-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colonies', '0001_initial'),
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cats', verbose_name='Foto')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='cat-thumbnails', verbose_name='Icono')),
                ('name', models.CharField(max_length=32, verbose_name='Nombre')),
                ('gender', models.BooleanField(blank=True, choices=[(False, 'Macho'), (True, 'Hembra')], null=True, verbose_name='Sexo')),
                ('sterilized', models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Sí')], null=True, verbose_name='Esterilizado')),
                ('sterlize_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de esterilización')),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'Presente'), (1, 'Fallecido'), (2, 'Desaparecido'), (3, 'Adoptado')], default=0, verbose_name='Estado')),
                ('frequency', models.PositiveSmallIntegerField(choices=[(0, 'Habitual'), (1, 'Ocasional'), (2, 'Raramente')], default=0, verbose_name='Frequencia de visita')),
                ('sociability', models.PositiveSmallIntegerField(choices=[(0, 'Mucho'), (1, 'Normal'), (2, 'Poco'), (3, 'Nada')], default=1, verbose_name='Sociable')),
                ('sighting_date', models.DateField(blank=True, null=True, verbose_name='Fecha de avistamiento')),
                ('record_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha de registro')),
                ('colony', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colonies.colony', verbose_name='Colonia')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diseases.disease', verbose_name='Enfermedades')),
                ('pictures', models.ManyToManyField(blank=True, related_name='cats', to='cats.CatPicture')),
            ],
        ),
    ]
