# Generated by Django 4.0.6 on 2024-07-28 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colonies', '0001_initial'),
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cats', verbose_name='Foto')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cat-photos', verbose_name='Icono')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='cat-thumbnails', verbose_name='Icono')),
                ('name', models.CharField(blank=True, max_length=32, null=True, verbose_name='Nombre')),
                ('gender', models.BooleanField(blank=True, choices=[(False, 'Macho'), (True, 'Hembra')], null=True, verbose_name='Sexo')),
                ('sterilized', models.BooleanField(default=False, verbose_name='Esterilizado')),
                ('sterlize_date', models.DateField(blank=True, null=True, verbose_name='Fecha de esterilización')),
                ('state', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Presente'), (1, 'Fallecido'), (2, 'Desaparecido'), (3, 'Adoptado')], default=0, null=True, verbose_name='Estado')),
                ('frequency', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Habitual'), (1, 'Ocasional')], default=0, null=True, verbose_name='Frecuencia de visita')),
                ('sociability', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Sí'), (1, 'Ocasional'), (2, 'No')], default=1, null=True, verbose_name='Sociable')),
                ('sighting_date', models.DateField(blank=True, null=True, verbose_name='Fecha de avistamiento')),
                ('record_date', models.DateField(auto_now=True, null=True, verbose_name='Fecha de registro')),
                ('colony', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colonies.colony', verbose_name='Colonia')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='diseases.disease', verbose_name='Afecciones')),
                ('pictures', models.ManyToManyField(blank=True, related_name='cats', to='cats.catpicture')),
            ],
        ),
    ]
