# Generated by Django 3.2.6 on 2024-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='sterilized',
            field=models.BooleanField(default=False, verbose_name='Esterilizado'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sterlize_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de esterilización'),
        ),
    ]
