# Generated by Django 3.2.6 on 2024-07-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20240712_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cat-thumbnails', verbose_name='Icono'),
        ),
    ]
