# Generated by Django 4.0.6 on 2024-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Adulto'), (1, 'Joven'), (2, 'Bebé')], default=0, null=True, verbose_name='Edad'),
        ),
    ]
