# Generated by Django 3.2.6 on 2024-07-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_auto_20240723_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cat-photos', verbose_name='Icono'),
        ),
    ]
