# Generated by Django 4.0.6 on 2024-07-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_cat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='frequency',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Habitual'), (1, 'Ocasional')], default=0, null=True, verbose_name='Frecuencia de visita'),
        ),
    ]
